language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 --exclude=migrations mmc
script:
  - make test
  - make coverage
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.13
  - DJANGO=1.5.8
  - DJANGO=1.6.5
branches:
  only:
    - master
