language: python
python:
  - "2.7"
  - "3.4"
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 --ignore=E402,F821 --exclude=migrations,south_migrations mmc
script:
  - make test
  - make coverage
env:
  - DJANGO=1.5.12
  - DJANGO=1.6.11
  - DJANGO=1.7.10
  - DJANGO=1.8.4
branches:
  only:
    - master
