language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 --ignore=E402 --exclude=migrations,south_migrations mmc
script:
  - make test
  - make coverage
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.15
  - DJANGO=1.5.10
  - DJANGO=1.6.7
branches:
  only:
    - master
