# Generated by Django 2.2.11 on 2020-05-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0018_auto_20160923_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmcemail',
            name='email',
            field=models.EmailField(help_text='Email will be used for send all exceptions from command.', max_length=254),
        ),
        migrations.AlterField(
            model_name='mmcemail',
            name='ignore',
            field=models.ManyToManyField(blank=True, help_text='Helpful for different teams. Choose script which you want to ignore.', to='mmc.MMCScript'),
        ),
        migrations.AlterField(
            model_name='mmcemail',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Email may be switched off for a little while.'),
        ),
        migrations.AlterField(
            model_name='mmchost',
            name='ignore',
            field=models.BooleanField(default=False, help_text='All logs from all scripts on this host will be ignored.'),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='calls',
            field=models.BigIntegerField(default=0, verbose_name='Number of calls'),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='enable_queries',
            field=models.BooleanField(default=False, help_text='Profile queries numbers.'),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='enable_triggers',
            field=models.BooleanField(default=False, help_text='Enable triggers for receive email notification, if threshold of counters will be exceeded'),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='ignore',
            field=models.BooleanField(default=False, help_text='All logs from this script will be ignored.'),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='interval_restriction',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Interval before script can be run again', null=True),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='one_copy',
            field=models.BooleanField(default=False, help_text='Only one copy of this script will be run.'),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='real_time',
            field=models.BooleanField(default=False, help_text='Real Time info about command (for long tasks).'),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='save_on_error',
            field=models.BooleanField(default=False, help_text='This flag can be used only for ignored commands.'),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='temporarily_disabled',
            field=models.SmallIntegerField(choices=[(0, 'Enabled'), (1, 'Disabled / Raise error'), (2, 'Disabled / Silence mode')], default=0, help_text='Temporarily disable script execution'),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='track_at_exit',
            field=models.BooleanField(default=True, help_text='Disable for uWSGI/Celery'),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='trigger_cpu',
            field=models.FloatField(blank=True, help_text='Set the threshold time for CPU', null=True),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='trigger_memory',
            field=models.FloatField(blank=True, help_text='Set the threshold MB for Memory', null=True),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='trigger_queries',
            field=models.FloatField(blank=True, help_text='Set the threshold number of queries', null=True),
        ),
        migrations.AlterField(
            model_name='mmcscript',
            name='trigger_time',
            field=models.FloatField(blank=True, help_text='Set the threshold sec for execution time', null=True),
        ),
    ]
