# Generated by Django 2.2.11 on 2020-05-21 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmc', '0019_auto_20200521_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mmclog',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mmc.MMCHost'),
        ),
        migrations.AlterField(
            model_name='mmclog',
            name='script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mmc.MMCScript'),
        ),
    ]
